name: Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up BuildTools
        run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Install CraftBukkit 1.8.8, 1.12.2, 1.15.2, 1.16.5
        run: |
          java -jar BuildTools.jar --rev 1.8.8 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.12.2 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.15.2 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.16.5 --compile craftbukkit
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'maven'
      - name: Install CraftBukkit 1.17.1, 1.18.2, 1.19.2, 1.19.3
        run: |
          java -jar BuildTools.jar --rev 1.17.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.18.2 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.19.2 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.19.3 --compile craftbukkit --remapped
      - name: Install PerWorldInventory
        run: |
          git clone https://github.com/Jannyboy11/perworldinventory-kt.git
          cd perworldinventory-kt
          mvn --batch-mode --update-snapshots clean package install -DskipTests=true
      - name: Compile InvSee++
        run: mvn --batch-mode --update-snapshots verify
      - name: Create tagged release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Spigot_Plugin/target/InvSee++.jar
            Spigot_Addon_Give/target/InvSee++_Give.jar
            Spigot_Addon_Clear/target/InvSee++_Clear.jar
