name: Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download BuildTools
        run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      # JDK 8: Needed for older versions
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Compile CraftBukkit 1.8.8, 1.12.2, 1.16.5
        run: |
          java -jar BuildTools.jar --rev 1.8.8 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.12.2 --compile craftbukkit
          java -jar BuildTools.jar --rev 1.16.5 --compile craftbukkit

      # JDK 17: Needed for mid versions
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'maven'

      - name: Compile CraftBukkit 1.17.1 to 1.20.4
        run: |
          java -jar BuildTools.jar --rev 1.17.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.18.2 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.19.4 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.20.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.20.4 --compile craftbukkit --remapped

      # JDK 21: Needed for latest versions
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'

      - name: Compile CraftBukkit 1.20.6 and 1.21.x
        run: |
          java -jar BuildTools.jar --rev 1.20.6 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 4287 --compile craftbukkit --remapped # Pre-release / Build number
          java -jar BuildTools.jar --rev 1.21.1 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.3 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.4 --compile craftbukkit --remapped
          java -jar BuildTools.jar --rev 1.21.5 --compile craftbukkit --remapped

      - name: Compile InvSee++
        run: mvn clean package install --batch-mode --update-snapshots

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InvSee++-build
          path: |
            InvSee++_Plugin/target/InvSee++.jar
            InvSee++_Give_Plugin/target/InvSee++_Give.jar
            InvSee++_Clear_Plugin/target/InvSee++_Clear.jar

      - name: Deploy Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-distribution: temurin
          java-version: 24
          custom-command: 'mvn package javadoc:aggregate -pl :invsee-plus-plus,:invsee-plus-plus_plugin,:invsee-plus-plus_common'
          target-folder: javadoc
          project: maven
